databases:
  - name: TheRialNews
    databaseName: therialnews_twf6
    user: therialnews_twf6_user
    plan: free

services:
  - type: web
    name: TheRialNews
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh && bundle exec rails db:migrate"
    startCommand: "bundle exec rails server -b 0.0.0.0"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: TheRialNews
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
